Imported Upstream version 3.25

diff --git a/examples++-load/load.link.in b/examples++-load/load.link.in
--- a/examples++-load/load.link.in
+++ b/examples++-load/load.link.in
@@ -9,6 +9,7 @@ FFCXXFLAGS='@CXXFLAGS@ @CPPFLAGS@'
 FFFFLAGS='@FFLAGS@'
 FFFLIBS='@FLIBS@'
 INCFF=
+if [ "@ENABLE_FFCS@" != "yes" ] ;then ffcs=0; else ffcs=1;fi 
 if [ -z "$CXX" ] ; then CXX='@CXX@' ; fi
 if [ -z "$MPICXX" ] ; then MPICXX="@MPICXX@" ; fi
 if [ -z "$MPI_LIB" ] ; then MPI_LIB="@MPI_LIB@" ; fi
@@ -123,7 +124,7 @@ while [ $# -ne 0 ]  ; do
 	-I*)    INC="$INC '$1'";;
 	-D*)    INC="$INC '$1'";;
 	-dll)   DLL="$DLL '$2'";shift;;
-	-[Ll]*)    LIBS="$LIBS $1" ;;
+	-[Ll]*)    LIBS="$LIBS '$1'" ;; # FFCS - 27/10/11 - need quotes for MPICH libraries in 'Program Files' under Windows
 	*.a)     LIBS="$LIBS $1" ;;
 	*.so)    LIBS="$LIBS $1" ;;
 	*.dll)   if [ -f "$1" ] ; then  LIBS="$LIBS '$1'"  
@@ -145,6 +146,11 @@ while [ $# -ne 0 ]  ; do
     esac
     shift
 done
+
+#  remove old file... FH sep 2013..
+SUF=@DYLIB_SUFFIX@
+rm $out.$SUF
+
 if [ -n "$autodep"  ] ; then
 #    echo "$thecommand" $args  `eval "'$dircommand/ff-get-dep'" -ff $files`
     argsdep=`eval "'$dircommand/ff-get-dep'" -ff $files`
@@ -152,11 +158,18 @@ if [ -n "$autodep"  ] ; then
      error=`echo "$argsdep"| grep ERROR`
      if [ -n "$error" ] ; then
 	 echo " ERROR in  auto dependance seach.  sorry : $error "
-	 exit 0;
+
+	 # FFCS - 28/11/11 - we need to stop compiling as soon as there is an error because we want a fixed set of features in
+	 # FFCS
+	 # return a error when FFCS enable .. FH. 
+	 echo " -- $error " >>Missing-plugins-@DYLIB_SUFFIX@.log
+	 exit $ffcs;
      fi
     echo eval "$thecommand" $args  $argsdep
     eval "$thecommand" $args  $argsdep
-    exit 0;
+
+    # FFCS needs an error exit code to make sure that all libraries are correctly compiled
+    exit $?;
 fi
 
 if [  -n "$onwin32" -a ! -f "$bin/libff.dll"  ] ; then 
@@ -174,29 +187,34 @@ if [ -n "$withmpi" ]; then  CXX=$MPICXX;fi
 test "$withmpi" = "yes" && WMPI_LIB="$MPI_LIB"
 
 INC="$INCFF $INC"  
-SUF=so
 SHARED="-shared"
 case "$WIN32$uu" in
     Darwin*) 
 #        echo "export MACOSX_DEPLOYMENT_TARGET=10.3"
 #	export MACOSX_DEPLOYMENT_TARGET=10.4
-	SUF=dylib
+#	SUF=dylib
 	SHARED="-bundle -undefined dynamic_lookup"  ;;
     win32-CYGWIN*|win32-win32)
         echo " Window without cygwin "
 	WMPI_LIB=''
         b="$bin"
-        LIBS=" '$b/libff.dll' $LIBS $DLL"
-        SHARED="-shared  -Wl,--enable-auto-import" #--unresolved-symbols=ignore-all
-        FLAGS= # '  -mno-cygwin '
-        SUF=dll;;
+        LIBS=" '$b/libff.dll' '$b/FreeFem++-api.dll' $LIBS $DLL"
+
+	# FFCS - 17/10/12 - --unresolved-symbols=ignore-all is not understood by the current mingw64 compilers
+        SHARED="-shared -Wl,--enable-auto-import"
+
+	# FFCS - 17/10/12 - -mno-cygwin is not understood by the current mingw64 compilers
+        ###FLAGS='  -mno-cygwin '
+#        SUF=dll
+	;;
     win32-cygwin-version)
         echo " cygwin-version "
 	WMPI_LIB=''
         b=$bin
         FLAGS=' '
         LIBS="'$b/libff.dll' $LIBS $DLL"
-        SUF=dll;;
+#        SUF=dll
+	;;
     FreeBSD|NetBSD)
 	SHARED="-shared" 
 	FLAGS='-fPIC';;
